### ISSUE TITLE
QR: QR string is missing scouter name in event list

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2020-scouting-app#10]
Expected result:
- eventList string ends with ScouterName

Actual result:
- Scouter Name only outputs in the setupList 

Note: We need this so Tableau can correctly link the 2 data sets together and prevent overlap/duplicates/conflicts.

**Comment by HenryRich14** [comment]
Added scouter name to the end of each line in the event list in the python script;
NOTE: the new script needs to be downloaded to the strategy laptop from GitHub or google drive
