### ISSUE TITLE
QR: QR string is outputting extra letter based on field side

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2020-scouting-app#11]
Expected result:
- output for starting location is one of the following values: L1, L2, C, R1, R2 regardless of field side

Actual result:
- output varies based on field side
- for left side of the field output is: LL1, LL2, LC, LR1, LR2
- for right side of the field output is: RL1, RL2, RC, RR1, RR2

**Comment by HenryRich14** [comment]
Used a substring to remove the extra letter when adding it to the QRString
