### ISSUE TITLE
Climb: When "Fell over" is enabled in Auton/Teleop park should still be enabled

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2020-scouting-app#12]
Expected result:
- turning on the fell over/died toggle should disable everything it does currently EXCEPT the "parked" toggle.

Actual result: 
- All the things are disabled

Note: Tyler Lucas rightfully pointed out that if a robot dies in the rendezvous point, they could still be considered parked at the end of the match, and we should capture that.

**Comment by HenryRich14** [comment]
Fixed the if statement so it wouldn't disable the parked toggle when fell over/died is selected
