### ISSUE TITLE
Auton/Teleop: Popup appears lower/higher than it needs to be

### ISSUE THREAD

**Issue by Arnavpmr** [Mercury1089/2020-scouting-app#5]
Expected Result: The top/bottom of the popup should be aligned closely with the scored/missed button

Actual Result: When a popup has been opened, the top/bottom of the popup appears farther from its designated button than it needs to be

To recreate:

Go to either the auton or teleop screen.  
Tap either the scored or missed button to launch a popup.

**Comment by HenryRich14** [comment]
We created a .png file with the carat so that it would be the right size.  The extra space has been removed.
