### ISSUE TITLE
Auton/Teleop: Swap +/- button position

### ISSUE THREAD

**Issue by sreffler** [Mercury1089/2020-scouting-app#6]
Expected result: - button is on the left, + button is on the right (closest to the counter)
Actual result: matches the wireframe (+ on the left, - on the right)

Note: Great job matching the wireframes, this was CORRECT in your initial build, But we realized during user testing that it's more natural for the + button to be on the right side.

**Comment by soullessjump** [comment]
The positions of the buttons have been successfully swapped
